### ISSUE TITLE
New

### ISSUE THREAD

**Issue by khaledalam173** [GDSimpson3/Personal-Projects_Personlich-Projekte#2]
SKV-Project/.SKV1666121475119/.SKV-D-0/SKV-F=00.txt

**Comment by khaledalam173** [comment]
[Uploading export-Khaled-173-1667599507.json.gz…]()

**Comment by khaledalam173** [comment]
Bye

**Comment by GDSimpson3** [comment]
wait?, the .SKV1666... file is a file that gets created when the project is run, it creates hidden files that have a unique name.

**Comment by GDSimpson3** [comment]
> Uploading export-Khaled-173-1667599507.json.gz…

please can you tell what the link is sorry.

**Comment by khaledalam173** [comment]
#4 #3
